title: Settings Mappings
type: object
required:
  - name
  - description
  - mappings
properties:
  name:
    type: string
  description:
    type: string
  mappings:
    type: object
    additionalProperties:
      type: [string, number, boolean, array]
    propertyNames:
      pattern: ^[a-z][a-z|A-Z|_]+$
